name = "zgzx-tst"
compatibility_date = "2025-04-15"
workers_dev = true

[site]
bucket = "./.next"

[build]
command = "npm run build"

[env.production]
name = "zgzx-tst-prod"
route = "zgzx-tst.pages.dev/*"

[env.staging]
name = "zgzx-tst-staging"
route = "staging.zgzx-tst.pages.dev/*" 